version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bruno
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bruno
      MYSQL_PASSWORD: wordpresspassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: bruno
      WORDPRESS_DB_PASSWORD: bruno
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
